name: Build
on: push
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: docker login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -P ${{ secrets.DOCKERHUB_ACCESSTOKEN }}
      - name: build docker image    
        run: docker build -t balu071/actions .
      - name: publish image to dockerhub
        run: docker push balu071/actions:latest
